basePath: /
definitions:
  controllers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: integer
      passwordHash:
        type: string
      phoneNumber:
        type: string
    required:
    - passwordHash
    - phoneNumber
    type: object
  models.UserRegistration:
    properties:
      password:
        minLength: 6
        type: string
      phoneNumber:
        type: string
    required:
    - password
    - phoneNumber
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample shopping API server.
  title: Shopping API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Sets up the routes for user-related endpoints
      produces:
      - application/json
      responses: {}
      summary: Register user routes
      tags:
      - users
swagger: "2.0"
